name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Install Python 3
        uses: actions/setup-python
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .
      - name: lint
        run: python3 -m pylint EFTLikelihood/*.py --fail-under=6.5
      - name: Run tests with pytest
        run: pytest -rP
